from running_modes.configurations.compound_sampling.sample_from_model_configuration import SampleFromModelConfiguration
from running_modes.configurations.compound_sampling.link_invent_sample_from_model_configuration import LinkInventSampleFromModelConfiguration
